### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kodxana** [Extraltodeus/multi-subject-render#1]
Error message:
```
Loading midas model weights ..
./models/midas/midas_v21_small-70d6b9c8.pt
100%|██████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:05<00:00,  7.36it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  7.53it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  7.59it/s]
Error completing request6:39,  8.24it/s]
Arguments: ('Background in 2DLyoko style', '', 'None', 'None', 40, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 4, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, False, '', 1, '', 0, '', True, False, False, 'Aelita2D standing with smile on face, (bokeh), (F1.8:1.2)\nJeremy2D standing looking at camera, (bokeh), (F1.8:1.2)', 5, 24, 12.5, 1000, 'Euler a', 0, 64, 64, '', 64, 7.5, 0.42, 'Euler a', 1600, 64, 1, 0, 92, True, True, True, False, False, '{inspiration}', None) {}
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "I:\stable-diffusion-webui\webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "I:\stable-diffusion-webui\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "I:\stable-diffusion-webui\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "I:\stable-diffusion-webui\extensions\multi-subject-render\scripts\multirender.py", line 203, in run
    p.prompt    = foregen_prompts[i] if len(foregen_prompts) > 1 else foregen_prompt
IndexError: list index out of range

```

**Comment by Extraltodeus** [comment]
Did you interrupt the generation? That message appears when you do that sometimes.

**Comment by trihardseven** [comment]
having a similar issue

**Comment by trihardseven** [comment]
```
Error completing request:22,  5.27it/s]
Arguments: ('sunflower field path, day, sun, bloom, grass, hill, (flowerbed :1.0) with (clouds :0.8) in the background, lush grass during day, soft lighting, beautiful glow, hill, river, (farm)', 'blue eyes, thick eyebrows, multiple males, lowres, bad anatomy, ((bad hands)), mutated hand, text, error, missing fingers, flat chest, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, bikini, username, blurry, artist name, purple skin, out of focus, multiple views, heterochromia, greyscale, big hands, fingerless gloves, two belly buttons', 'None', 'None', 20, 13, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 832, 832, False, 0.7, 0, 0, 10, '<div class="dynamic-prompting">\n    <h3><strong>Combinations</strong></h3>\n\n    Choose a number of terms from a list, in this case we choose two artists: \n    <code class="codeblock">{2$$artist1|artist2|artist3}</code><br/>\n\n    If $$ is not provided, then 1$$ is assumed.<br/><br/>\n\n    If the chosen number of terms is greater than the available terms, then some terms will be duplicated, otherwise chosen terms will be unique. This is useful in the case of wildcards, e.g.\n    <code class="codeblock">{2$$__artist__}</code> is equivalent to <code class="codeblock">{2$$__artist__|__artist__}</code><br/><br/>\n\n    A range can be provided:\n    <code class="codeblock">{1-3$$artist1|artist2|artist3}</code><br/>\n    In this case, a random number of artists between 1 and 3 is chosen.<br/><br/>\n\n    Wildcards can be used and the joiner can also be specified:\n    <code class="codeblock">{{1-$$and$$__adjective__}}</code><br/>\n\n    Here, a random number between 1 and 3 words from adjective.txt will be chosen and joined together with the word \'and\' instead of the default comma.\n\n    <br/><br/>\n\n    <h3><strong>Wildcards</strong></h3>\n    <p class="wildcard">__adjective__</p><p class="wildcard">__skincolor__</p><p class="wildcard">__sports__</p><p class="wildcard">__style__</p><p class="wildcard">__styles__</p><p class="wildcard">__subject__</p><p class="wildcard">__swimwear__</p><p class="wildcard">__tech__</p><p class="wildcard">__time__</p><p class="wildcard">__view__</p><p class="wildcard">__weather__</p>\n\n    <br/>\n    If the groups wont drop down click <strong onclick="check_collapsibles()" style="cursor: pointer">here</strong> to fix the issue.\n\n    <br/><br/>\n\n    <code class="codeblock">WILDCARD_DIR: H:\\AI Image generatore\\stable-diffusion-webui\\extensions\\sd-dynamic-prompts\\wildcards</code><br/>\n    <small onload="check_collapsibles()">You can add more wildcards by creating a text file with one term per line and name is mywildcards.txt. Place it in H:\\AI Image generatore\\stable-diffusion-webui\\extensions\\sd-dynamic-prompts\\wildcards. <code class="codeblock">__&#60;folder&#62;/mywildcards__</code> will then become available.</small>\n</div>\n\n', True, False, 1, False, False, False, 100, 0.7, False, False, False, False, False, False, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, '\n            <h3><strong>Combinations</strong></h3>\n            Choose a number of terms from a list, in this case we choose two artists\n            <code>{2$$artist1|artist2|artist3}</code>\n            If $$ is not provided, then 1$$ is assumed.\n            <br>\n            A range can be provided:\n            <code>{1-3$$artist1|artist2|artist3}</code>\n            In this case, a random number of artists between 1 and 3 is chosen.\n            <br/><br/>\n\n            <h3><strong>Wildcards</strong></h3>\n            <p>Available wildcards</p>\n            <ul>\n        <li>__adjective__</li><li>__skincolor__</li><li>__sports__</li><li>__style__</li><li>__styles__</li><li>__subject__</li><li>__swimwear__</li><li>__tech__</li><li>__time__</li><li>__view__</li><li>__weather__</li></ul>\n            <br/>\n            <code>WILDCARD_DIR: scripts/wildcards</code><br/>\n            <small>You can add more wildcards by creating a text file with one term per line and name is mywildcards.txt. Place it in scripts/wildcards. <code>__mywildcards__</code> will then become available.</small>\n        ', False, False, False, '', 1, '', 0, '', True, False, False, '\n            <h3><strong>Combinations</strong></h3>\n            Choose a number of terms from a list, in this case we choose two artists\n            <code>{2$$artist1|artist2|artist3}</code>\n            If $$ is not provided, then 1$$ is assumed.\n            <br>\n            A range can be provided:\n            <code>{1-3$$artist1|artist2|artist3}</code>\n            In this case, a random number of artists between 1 and 3 is chosen.\n            <br/><br/>\n\n            <h3><strong>Wildcards</strong></h3>\n            <p>Available wildcards</p>\n            <ul>\n        <li>__adjective__</li><li>__skincolor__</li><li>__sports__</li><li>__style__</li><li>__styles__</li><li>__subject__</li><li>__swimwear__</li><li>__tech__</li><li>__time__</li><li>__view__</li><li>__weather__</li></ul>\n            <br/>\n            <code>WILDCARD_DIR: scripts/wildcards</code><br/>\n            <small>You can add more wildcards by creating a text file with one term per line and name is mywildcards.txt. Place it in scripts/wildcards. <code>__mywildcards__</code> will then become available.</small>\n        ', False, False, False, '', 1, '', 0, '', True, False, False, '', 'None', 30, 4, 0, 0, False, 'None', '<br>', 'None', 30, 4, 0, 0, 4, 0.4, True, 32, '(farm girl), medium light red hair, hourglass figure, bare back, shoulders, armpits, cleavage, looking at viewer,  seductive smile, parted lips, sweat,\nside braid, swept bangs, detailed eyes, beautiful eyes, amber eyes, (freckles:1.01), (fair skin:1.0) and {medium breasts|large breasts}, midriff, navel, (skindendation),\ncowboy hat, straw hat, denim, off shoulder, ((tied shirt)), cropped shirt, denim shorts,', 5, 24, 12.5, 1000, 'DDIM', 0, 64, 64, '', 64, 7.5, 0.42, 'DPM++ 2S a Karras', 64, 64, 1, 0, 92, True, True, True, False, False) {}
Traceback (most recent call last):
  File "H:\AI Image generatore\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "H:\AI Image generatore\stable-diffusion-webui\webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "H:\AI Image generatore\stable-diffusion-webui\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "H:\AI Image generatore\stable-diffusion-webui\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "H:\AI Image generatore\stable-diffusion-webui\extensions\multi-subject-render\scripts\multirender.py", line 212, in run
    p.prompt    = foregen_prompts[i] if len(foregen_prompts) > 1 else foregen_prompt
IndexError: list index out of range
```
Seems like some kind of interaction with dynamic prompts extension?

**Comment by trihardseven** [comment]
Also, I have a question. If each line is a foreground subject, does that mean its impossible to use long prompts for a single character? Thanks, really like the idea behind the extension.

**Comment by Miyuutsu** [comment]
The issue here seems to be having a larger number of foreground images set than of foreground prompts provided. Ran into it myself a few times.



> Also, I have a question. If each line is a foreground subject, does that mean its impossible to use long prompts for a single character? Thanks, really like the idea behind the extension.

By "new line" it means that literally, if you're not specifically starting a new line with enter or such then it's the same line.

**Comment by Extraltodeus** [comment]
Yes exactly. I'm not talking about the automatic soft wrap in the text box but entering a newline manually.

**Comment by trihardseven** [comment]
> Yes exactly. I'm not talking about the automatic soft wrap in the text box but entering a newline manually.

So copy and pasting a 10 line prompt from my notepad should be fine, as long as I don't press enter? Maybe it would be more clear if it was done in paragraphs like this:

((masterpiece)), (((best quality))), ((ultra-detailed)), ((illustration)), (an extremely delicate and beautiful), (1boy), muscular boy, short messy white hair

((masterpiece)), (((best quality))), ((ultra-detailed)), ((illustration)), (an extremely delicate and beautiful), (1girl), curvy, long blonde hair

**Comment by Extraltodeus** [comment]
> So copy and pasting a 10 line prompt from my notepad should be fine, as long as I don't press enter? 

Yes!
I'm closing this ticket since it's not an issue. Feel free to create a new discussion in the discussion tab if you have more question.
