### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.simple_depthmap'

### ISSUE THREAD

**Issue by leppie** [Extraltodeus/multi-subject-render#2]
Using the extention install method from URL.

```
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "G:\stable-diffusion-webui\webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "G:\stable-diffusion-webui\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "G:\stable-diffusion-webui\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "G:\stable-diffusion-webui\extensions\multi-subject-render\scripts\multirender.py", line 112, in run
    import scripts.simple_depthmap as sdmg
ModuleNotFoundError: No module named 'scripts.simple_depthmap'
```

Adding `simple_depthmap.py` to the root scripts folder resolves the issue.

So something up with `import` from an extension. (Dont know python, so cant help).

BTW this extension looks awesome!

**Comment by Extraltodeus** [comment]
Oh yes indeed! I wrote the thing while having it in the scripts folder.

**Comment by HugoSega** [comment]
the image is generated but I get this error. 

File "/Users/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/Users/stable-diffusion-webui/webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "/Users/stable-diffusion-webui/modules/txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "/Users/stable-diffusion-webui/modules/scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "/Users/stable-diffusion-webui/extensions/multi-subject-render/scripts/multirender.py", line 215, in run
    proc = process_images(p)
  File "/Users/stable-diffusion-webui/modules/processing.py", line 430, in process_images
    res = process_images_inner(p)
  File "/Users/stable-diffusion-webui/modules/processing.py", line 496, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/Users/stable-diffusion-webui/modules/processing.py", line 646, in init
    width_ratio = self.width / self.firstphase_width
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'

**Comment by Extraltodeus** [comment]
I fixed the path problem
d2e913f7446332acc21a6fc62dad4e9acc6d5824

**Comment by leppie** [comment]
> the image is generated but I get this error.

I got this when using high res fix

**Comment by Extraltodeus** [comment]
> I got this when using high res fix

Oh yeah you don't need it. Use the blend size slider at the end. It will trigger it.
