### ISSUE TITLE
no module 'timm.models.beit'

### ISSUE THREAD

**Issue by DaniByKellogs** [Extraltodeus/multi-subject-render#42]
Launching Web UI with arguments: --enable-insecure-extension-access --share --gradio-debug --medvram --disable-safe-unpickle --xformers
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Error loading script: simple_depthmap.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/multi-subject-render/scripts/simple_depthmap.py", line 11, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "/content/stable-diffusion-webui/repositories/midas/midas/dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "/content/stable-diffusion-webui/repositories/midas/midas/blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "/content/stable-diffusion-webui/repositories/midas/midas/backbones/beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

Error loading script: depthmap.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 40, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/backbones/beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

**Comment by mykeehu** [comment]
I got this solution:
https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/74#issuecomment-1400949153
