### ISSUE TITLE
Error verifying pickled file 

### ISSUE THREAD

**Issue by levelmaxcat** [Extraltodeus/multi-subject-render#47]
Error verifying pickled file from C:\Users\hunte\stable-diffusion-webui\models\Codeformer\codeformer-v0.1.0.pth:
Traceback (most recent call last):
  File "C:\Users\hunte\stable-diffusion-webui\modules\safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "C:\Users\hunte\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Users\hunte\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by levelmaxcat** [comment]
i set COMMANDLINE_ARGS=--disable-safe-unpickle

but got this


RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
