### ISSUE TITLE
Appears to be broken now: ModuleNotFoundError: No module named 'timm.models.beit'

### ISSUE THREAD

**Issue by abbator** [Extraltodeus/multi-subject-render#53]
Requesting different MiDaS models does not change this. All settings produce the "ModuleNotFoundError: No module named 'timm.models.beit'" error.

**Comment by HeavyTony2** [comment]
Same here,
```
    processed = script.run(p, *script_args)
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions\multi-subject-render\scripts\multirender.py", line 145, in run
    sdmg = module_from_file("simple_depthmap",'extensions/multi-subject-render/scripts/simple_depthmap.py')
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions\multi-subject-render\scripts\multirender.py", line 21, in module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions/multi-subject-render/scripts/simple_depthmap.py", line 11, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\repositories\midas\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\repositories\midas\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

```


edit: wait, it seems to be a Midas problem


Error loading script: simple_depthmap.py
```
Traceback (most recent call last):
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions\multi-subject-render\scripts\simple_depthmap.py", line 11, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\repositories\midas\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\repositories\midas\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'
```

**Comment by HeavyTony2** [comment]
It seems to work since I did `it checkout f28885a` with Midas repository, but it's weird considering current git version of Midas has been the same since january.
